use_frameworks!

target 'EncryptedDATAStack_Example' do
  pod 'EncryptedDATAStack', :path => '../'
  pod 'DATASource’, '~> 6'

  target 'EncryptedDATAStack_Tests' do
    inherit! :search_paths

  end
end