use_frameworks!

target 'EncryptedDATAStack_Example' do
  pod 'EncryptedDATAStack', :path => '../'
  pod 'DATASource’, '~> 7.0.2'
  pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'

  target 'EncryptedDATAStack_Tests' do
    inherit! :search_paths

  end
end
